"""initial

Revision ID: bee2fae6a7f1
Revises: 
Create Date: 2024-05-14 14:20:46.640069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee2fae6a7f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('f_name', sa.String(length=100), nullable=False),
    sa.Column('m_name', sa.String(length=100), nullable=False),
    sa.Column('l_name', sa.String(length=100), nullable=False),
    sa.Column('roll_no', sa.String(length=50), nullable=True),
    sa.Column('age', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_no', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.String(length=20), nullable=False),
    sa.Column('admission_date', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('adharcard_no', sa.String(length=12), nullable=False),
    sa.Column('cast', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('fees', sa.String(length=10), nullable=False),
    sa.Column('hsc_percentage', sa.Float(precision=10), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
